language: c
script: asdf plugin-test python https://github.com/tuvistavie/asdf-python.git
before_script:
  - git clone https://github.com/tuvistavie/asdf.git --branch plugin-test asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
